### ISSUE TITLE
Error in ft.dfs

### ISSUE THREAD

**Issue by am610** [Featuretools/predict-remaining-useful-life#1]
when I try this snippet : 
`fm, features = ft.dfs(entityset=es, 
                      target_entity='engines',
                      agg_primitives=['last', 'max', 'min'],
                      trans_primitives=[],
                      cutoff_time=cutoff_times,
                      max_depth=3,
                      verbose=True)`

`fm.to_csv('simple_fm.csv')`

I get 

> AttributeError: 'str' object has no attribute 'input_types'

**Comment by kmax12** [comment]
@am610 what version of Featuretools are you using? Can you make sure you are on 0.2.1?

**Comment by am610** [comment]
@kmax12 , yes I am, however I installed with pip , following the instruction here "https://docs.featuretools.com/getting_started/install.html" 
But the run command : 
`make installdeps`

gives me error, 

`make: *** No rule to make target `installdeps'.  Stop.`

**Comment by kmax12** [comment]
that is to install for development. you should only need to run `pip install featuretools`

then can you run the following to make sure you've installed correctly

```
$ python
Python 3.6.4 (default, Dec 30 2017, 13:28:16) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import featuretools as ft
>>> ft.__version__
'0.2.1'
```

**Comment by am610** [comment]
Thanks, I tried the suggestion, and indeed my version is older one 

`>>> ft.__version__
 '0.1.19'`

How to upgrade now ?

thanks

**Comment by kmax12** [comment]
try `pip install --upgrade featuretools`.

I'm going to close this issue for now. Let us know if there any other questions
