### ISSUE TITLE
Error from CidCe

### ISSUE THREAD

**Issue by htcml** [Featuretools/predict-remaining-useful-life#13]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-15-a32d2f7e5759> in <module>
----> 1 from featuretools.tsfresh import CidCe
      2 
      3 fm, features = ft.dfs(
      4     entityset=es,
      5     target_entity='engines',

ModuleNotFoundError: No module named 'featuretools.tsfresh'

**Comment by thehomebrewnerd** [comment]
@htcml To run this notebook you need to have the `featuretools.tsfresh` module installed. Please make sure you have all the packages listed in the `requirements.txt` file installed in your environment. 

If you are using pip you can simply run `pip install -r requirements.txt` to install everything that should be needed for this notebook.
