### ISSUE TITLE
Alternative to CidCe from featuretools_tsfresh_primitives v0.1.3

### ISSUE THREAD

**Issue by josemariagarcia95** [Featuretools/predict-remaining-useful-life#15]
I'm learning how to use Featuretools and I've made it to a snippet which is right below this paragraph:

```python
from featuretools.tsfresh import CidCe
import featuretools as ft

fm, features = ft.dfs(
    entityset=es,
    target_entity='engines',
    agg_primitives=['last', 'max', CidCe(normalize=False)],
    trans_primitives=[],
    chunk_size=.26,
    cutoff_time=cutoff_time_list[0],
    max_depth=3,
    verbose=True,
)

fm.to_csv('advanced_fm.csv')
fm.head()
```
However, I get an error because CidCe cannot be imported from tsfresh, which is caused because apparently CidCe was on featuretools_tsfresh_primitives version 0.1.3, but it's not anymore, and since I don't know what it is I don't know how to try to substitute it (I wanna use it the last version of tsfresh, which is 1.0.2).

**Comment by thehomebrewnerd** [comment]
@josemariagarcia95 I think this is the same issue as posted here: https://github.com/alteryx/featuretools-tsfresh-primitives/issues/104

As a result I am going to close this one.

Also, you may have figured this out already, but this is a very old version of the demo notebook and not being maintained any longer. Many of the calls are now outdated. A slightly newer version can be found here, but even those examples are starting to get outdated: https://github.com/alteryx/open_source_demos
