### ISSUE TITLE
utils module

### ISSUE THREAD

**Issue by v1118** [Featuretools/predict-remaining-useful-life#3]
import numpy as np
import pandas as pd
import featuretools as ft
import utils

utils.download_data()

data_path = np.genfromtxt('RUL_FD002.txt')
data = utils.load_data(data_path)
data.head()

On running the above code I am getting the following errors
AttributeError: module 'utils' has no attribute 'download_data'
AttributeError: module 'utils' has no attribute 'load_data'

**Comment by bukosabino** [comment]
Hi @v1118,

We have checked the demo and we found some problems in 'download_data' function. So, We recommend you [download the data](https://ti.arc.nasa.gov/tech/dash/groups/pcoe/prognostic-data-repository/#turbofan) manually and run the updated notebooks.

Please, follow the instructions in the [README.md](https://github.com/Featuretools/predict-remaining-useful-life/blob/master/README.md)

Let me know if you have some more problem!
