### ISSUE TITLE
Missing Cells?

### ISSUE THREAD

**Issue by Lewington-pitsos** [Featuretools/predict-remaining-useful-life#6]
the section **Step 3: Feature Selection and Scoring** in the Advanced Featuretools notebook has 2 explanatory markup cells but no code cells. 

It seems like there is meant to be some code cells. If I'm wrong let me know.

Good notebooks otherwise.

**Comment by kmax12** [comment]
The content described in step 3 is in fact in the cells for step 2. It's the code related to feature selection that looks like 

```
if do_selection:
    reg2 = RandomForestRegressor(n_jobs=3)
    selector = RFE(reg2, int(hyperparams[2]), step=25)
    selector.fit(X_train, y_train)
    X_train = selector.transform(X_train)
    X_test = selector.transform(X_test)
    selectors.append(selector)
reg.fit(X_train, y_train)
regs.append(reg)
```

I agree that the organization could be a bit better. If you wanted to make changes to this notebook to make it more clear, we'd certainly welcome a PR!
